### ISSUE TITLE
Internet check fails "Host has no internet connection..."

### ISSUE THREAD

**Issue by brenner-tobias** [brenner-tobias/addon-cloudflared#166]
### The problem

(Copying the issue from the [HA Community](https://community.home-assistant.io/t/new-add-on-cloudflared/361637/262) here):
I am currently running into an issue where the tunneling using freenom and cloudflared addon is seeming to not have an internet connection.

### What version of Cloudflared has the issue?

2.0.13

### What was the last working version of Cloudflared?

2.0.12

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
56-rc: info: service s6rc-oneshot-runner successfully started
56-rc: info: service fix-attrs: starting
56-rc: info: service fix-attrs successfully started
56-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/ee-banner.sh
Add-on: Cloudflared
Use a Cloudflared tunnel (formerly Argo Tunnel) to remotely connect to Home Assistant without opening any ports
Add-on version: 2.0.13
You are running the latest version of this add-on.
System: Home Assistant 05 8.5
(amd64 / generic-x86-64)
Home Assistant Core: 2022.8.6
Home Assistant Supervisor: 2022.08.3
Please, share the above information when looking for help
or support in,
e.g.,
GitHub. forums or the Discord chat.
cont-init: info: /etc/cont-init.d/00-banner.sh exited e
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited e
56-rc: info: service legacy-cont-init successfully started
56-rc: info: service init-cloudflared-log: starting
56-rc: info: service init-cloudflared-log successfully started
56-rc: info: service init-cloudflared-config: starting
[22:53:25] ERROR: Host has no internet connection, waiting 30 seconds...
```

### Steps to reproduce the issue

Start HomeAssistant

**Comment by younesetre** [comment]
Sorry for posting in another section

My configuration

Version of Cloudflared has the issue
2.0.13

 Last working version of Cloudflared before update
2.0.12

System of installation I am running?
Home Assistant OS


After the last update for version 2.0.13, I can't connect with my server.
I have the following errors in logs  :

cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-cloudflared-log: starting
s6-rc: info: service init-cloudflared-log successfully started
s6-rc: info: service init-cloudflared-config: starting
[11:28:27] ERROR: Host has no internet connection, waiting 30 seconds...
[11:28:58] ERROR: Host has no internet connection, waiting 30 seconds...
[11:29:29] ERROR: Host has no internet connection, waiting 30 seconds...
[11:30:00] ERROR: Host has no internet connection, waiting 30 seconds...
[11:30:31] ERROR: Host has no internet connection, waiting 30 seconds...
[11:31:03] ERROR: Host has no internet connection, waiting 30 seconds...

**Comment by brenner-tobias** [comment]
No problem at all. Two questions:

1. Are you sure that your HA has a working internet connection?
1. Do you have an outbound firewall in your network that might prevent a ping to 1.1.1.1 from working?

**Comment by brenner-tobias** [comment]
I just updated the logic that tests the internet connection. Can you please check using the [edge repository](https://github.com/brenner-tobias/ha-addons-edge) if this resolves your issue @younesetre?

**Comment by Mdrede** [comment]
I have same problem it appears after the last update

**Comment by brenner-tobias** [comment]
> I have same problem it appears after the last update

did you check the newest version on the edge repository?

**Comment by Mdrede** [comment]
Yes I did, same issue

**Comment by Mdrede** [comment]
![Screenshot_20220825-214335_Chrome.jpg](https://user-images.githubusercontent.com/98788481/186743843-358ed8dc-14d7-47ba-8a1a-a171af9d7617.jpg)

**Comment by brenner-tobias** [comment]
ok, I know it sounds strange, but are you sure your HA has a working internet connection?

**Comment by younesetre** [comment]
Yes i am sure that my HA is connected to internet.
I don't have a firewall.
I had doubts with Adguard addon but even after stopping it, I still have the same problem

**Comment by younesetre** [comment]
here is ping google.com

![image](https://user-images.githubusercontent.com/6561267/186787544-2bef5ca8-3eef-427d-9551-3b137e57b802.png)

**Comment by Mdrede** [comment]
Yes I did ping google, it's working

**Comment by Mdrede** [comment]
This issue appear after the last update

**Comment by Mdrede** [comment]
I'm using home assistant

**Comment by brenner-tobias** [comment]
@elcajon do you have any idea whats not working here?

**Comment by zuccospooky** [comment]
With the standard Cloudflared addon I have the same "no internet connection". I tried the edge addon and everything works fine thank you.


This is my build
Add-on version: a104a16
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.8.7
 Home Assistant Supervisor: 2022.08.3

**Comment by elcajon** [comment]
> @elcajon do you have any idea whats not working here?

I assume that this issue is ISP/router/network specific because Cloudflare seems to be blocked. Maybe we can implement something like 1.1.1.1 OR 8.8.8.8 but maybe we should just diable all the checks and set up some Docker healthcheck script which can be activated / deactivated by toggling the switch.

**Comment by jturner421** [comment]
I cannot resolve 1.1.1.1 either.  Works with 1.0.0.1.  Tried the edge branch as suggested by @zuccospooky but no joy.

**Comment by elcajon** [comment]
@brenner-tobias The next [release of cloudflared](https://github.com/cloudflare/cloudflared/issues/724) should fix this issue by retrying to reconnect indefinitely, if this is working we should consider removing the health checks and watchdog stuff. What do you think?

**Comment by brenner-tobias** [comment]
Totally agree, I would love to keep the add-on as simple as possible, so let's hope for a soon Cloudflared release.

**Comment by jturner421** [comment]
As a follow up to my earlier comment, I discovered that my Pi-Hole setup was causing the problem resolving 1.1.1.1.  Once that was resolved, the add-on worked wonderfully.

**Comment by elcajon** [comment]
Good to hear, closing this for now. 👍🏻

**Comment by younesetre** [comment]
Too bad I was waiting impatiently for this update 2.0.14 but I still have the same problem

![image](https://user-images.githubusercontent.com/6561267/188000898-13b7c27d-0299-44f9-af36-ec38ed8fc961.png)

**Comment by brenner-tobias** [comment]
The update does not really address the issue that you still seem to have. We just released a new Cloudflared Version, which includes an automatic re-connect.
This means that we can now remove our own internet check, which gives you the error above. Nevertheless, we wanted to keep it runnig for some time before removing our own checks.
Now thinking about it, I guess we can do that right now, since we can always roll back. @elcajon: since you implemented the services part: Do you think you can remove all the "overhead" of the health check? I still think that watchdog (or at least the general idea of it to restart the add-on if it crashes) would make sense in its most basic way, if this does not introduce any problems

**Comment by younesetre** [comment]
Thanks

**Comment by brenner-tobias** [comment]
I just released 2.0.15 which includes the fix and the clean up. Thanks @elcajon

**Comment by younesetre** [comment]
Issue solved with the new update 2.0.15
Thanks a lot
